[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
usdv_bridge = "EjqTB7zPPHb26icpdv1Si1uYzE7WpNweRe4XyeXphC2Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/seal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
